### ISSUE TITLE
is_status_class has been deprecated and removed from Mojolicious 7.31

### ISSUE THREAD

**Issue by Grinnz** [jberger/Mojolicious-Command-nopaste#7]
Used in various service handlers. Should be replaced with is_success (with a dep on Mojolicious 7.13) or some usage of $tx->success/$tx->error for compatibility.

**Comment by jberger** [comment]
Bah I missed this one in all the discussion of Mojo::File. Thanks

**Comment by jberger** [comment]
Thanks again!
